
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class Admin_fn extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    ResultSet rs4=null;
    ResultSet rs8=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
     PreparedStatement pst2=null;
     PreparedStatement pst3=null;
     PreparedStatement pst4=null;
     PreparedStatement pst5=null;
     PreparedStatement pst6=null;
     PreparedStatement pst7=null;
     PreparedStatement pst8=null;
    public Admin_fn() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        GregorianCalendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(+day+"/"+(month+1)+"/"+year);
        int hour=cal.get(Calendar.AM_PM);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time.setText(+hour+":"+minute+":"+second);
        //multiple_fn.removeAll();
    }
public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        view_project = new javax.swing.JButton();
        view_team = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        teachers = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        multiple_fn = new javax.swing.JPanel();
        insert_fn = new javax.swing.JPanel();
        for_options = new javax.swing.JPanel();
        in_stud = new javax.swing.JButton();
        inteamproj = new javax.swing.JButton();
        background5 = new javax.swing.JLabel();
        in_student = new javax.swing.JPanel();
        reset3 = new javax.swing.JButton();
        submit3 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        projid2 = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        sphone = new javax.swing.JLabel();
        usn = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        susn = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        team_id = new javax.swing.JLabel();
        mail1 = new javax.swing.JLabel();
        smail = new javax.swing.JTextField();
        idteam = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        background11 = new javax.swing.JLabel();
        team_proj_in = new javax.swing.JPanel();
        projid = new javax.swing.JLabel();
        proj_id = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        id_proj = new javax.swing.JTextField();
        tm_id = new javax.swing.JLabel();
        teachername = new javax.swing.JLabel();
        tmid = new javax.swing.JTextField();
        tmname = new javax.swing.JTextField();
        proj_name = new javax.swing.JTextField();
        teacher_id = new javax.swing.JTextField();
        teach_id = new javax.swing.JLabel();
        reset2 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        view_proj = new javax.swing.JPanel();
        projtable = new javax.swing.JScrollPane();
        viewproj = new javax.swing.JTable();
        background3 = new javax.swing.JLabel();
        view_tm = new javax.swing.JPanel();
        teamtable = new javax.swing.JScrollPane();
        viewteam = new javax.swing.JTable();
        background4 = new javax.swing.JLabel();
        view_teacher = new javax.swing.JPanel();
        allteacher = new javax.swing.JScrollPane();
        teacher_view = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        date_time = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(51, 51, 51));

        insert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/spreadsheet.png"))); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        insert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                insertKeyPressed(evt);
            }
        });

        view_project.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        view_project.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/augmented-reality (1).png"))); // NOI18N
        view_project.setText("VIEW PROJECTS");
        view_project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_projectActionPerformed(evt);
            }
        });

        view_team.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        view_team.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/augmented-reality.png"))); // NOI18N
        view_team.setText("VIEW TEAMS");
        view_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_teamActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by (1).png"))); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        teachers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        teachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/google-glasses-tool-on-bald-male-head-from-side-view.png"))); // NOI18N
        teachers.setText("VIEW TEACHER");
        teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(view_project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_team, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teachers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(view_project, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(view_team, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(teachers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 228, 540);

        background.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 998, 540);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(226, 0, 2, 540);

        multiple_fn.setPreferredSize(new java.awt.Dimension(600, 540));
        multiple_fn.setLayout(new java.awt.CardLayout());

        insert_fn.setLayout(new java.awt.CardLayout());

        for_options.setLayout(null);

        in_stud.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        in_stud.setText("STUDENT");
        in_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_studActionPerformed(evt);
            }
        });
        for_options.add(in_stud);
        in_stud.setBounds(190, 130, 150, 23);

        inteamproj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inteamproj.setText("TEAM AND PROJECT");
        inteamproj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteamprojActionPerformed(evt);
            }
        });
        for_options.add(inteamproj);
        inteamproj.setBounds(370, 130, 141, 23);

        background5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        for_options.add(background5);
        background5.setBounds(0, 0, 998, 540);

        insert_fn.add(for_options, "card6");

        in_student.setLayout(null);

        reset3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        reset3.setText("RESET");
        reset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset3ActionPerformed(evt);
            }
        });
        in_student.add(reset3);
        reset3.setBounds(530, 430, 110, 24);

        submit3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enter.png"))); // NOI18N
        submit3.setText("SUBMIT");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });
        in_student.add(submit3);
        submit3.setBounds(400, 430, 110, 24);

        back1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        back1.setText("BACK");
        back1.setMaximumSize(new java.awt.Dimension(111, 33));
        back1.setMinimumSize(new java.awt.Dimension(111, 33));
        back1.setPreferredSize(new java.awt.Dimension(111, 33));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        in_student.add(back1);
        back1.setBounds(270, 430, 110, 26);

        projid2.setBackground(new java.awt.Color(0, 0, 0));
        projid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        projid2.setForeground(new java.awt.Color(255, 255, 255));
        projid2.setText("ENTER STUDENT DETAILS:-");
        in_student.add(projid2);
        projid2.setBounds(410, 20, 290, 40);

        DOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("Date Of Birth :");
        in_student.add(DOB);
        DOB.setBounds(280, 150, 130, 40);

        sphone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sphone.setForeground(new java.awt.Color(255, 255, 255));
        sphone.setText("Phone :");
        sphone.setMaximumSize(new java.awt.Dimension(95, 25));
        sphone.setMinimumSize(new java.awt.Dimension(95, 25));
        sphone.setPreferredSize(new java.awt.Dimension(95, 25));
        in_student.add(sphone);
        sphone.setBounds(280, 200, 130, 40);

        usn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usn.setForeground(new java.awt.Color(255, 255, 255));
        usn.setText("USN :");
        in_student.add(usn);
        usn.setBounds(280, 70, 120, 40);

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name :");
        name.setMaximumSize(new java.awt.Dimension(95, 25));
        name.setMinimumSize(new java.awt.Dimension(95, 25));
        name.setPreferredSize(new java.awt.Dimension(95, 25));
        in_student.add(name);
        name.setBounds(280, 110, 120, 40);

        susn.setMaximumSize(new java.awt.Dimension(95, 35));
        susn.setMinimumSize(new java.awt.Dimension(95, 25));
        susn.setPreferredSize(new java.awt.Dimension(95, 30));
        susn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                susnActionPerformed(evt);
            }
        });
        in_student.add(susn);
        susn.setBounds(420, 80, 220, 30);

        sname.setMaximumSize(new java.awt.Dimension(95, 35));
        sname.setMinimumSize(new java.awt.Dimension(95, 25));
        sname.setPreferredSize(new java.awt.Dimension(95, 30));
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        in_student.add(sname);
        sname.setBounds(420, 120, 220, 30);

        phone.setMaximumSize(new java.awt.Dimension(95, 28));
        phone.setMinimumSize(new java.awt.Dimension(95, 25));
        phone.setPreferredSize(new java.awt.Dimension(95, 28));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        in_student.add(phone);
        phone.setBounds(420, 210, 220, 28);

        address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address :");
        in_student.add(address);
        address.setBounds(280, 250, 120, 40);

        add.setColumns(20);
        add.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        in_student.add(jScrollPane1);
        jScrollPane1.setBounds(420, 260, 220, 50);

        team_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        team_id.setForeground(new java.awt.Color(255, 255, 255));
        team_id.setText("Team ID :");
        team_id.setMaximumSize(new java.awt.Dimension(95, 25));
        team_id.setMinimumSize(new java.awt.Dimension(95, 25));
        team_id.setPreferredSize(new java.awt.Dimension(95, 25));
        in_student.add(team_id);
        team_id.setBounds(280, 370, 120, 40);

        mail1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mail1.setForeground(new java.awt.Color(255, 255, 255));
        mail1.setText("E-mail :");
        in_student.add(mail1);
        mail1.setBounds(280, 320, 120, 40);

        smail.setMaximumSize(new java.awt.Dimension(95, 28));
        smail.setMinimumSize(new java.awt.Dimension(95, 25));
        smail.setPreferredSize(new java.awt.Dimension(95, 28));
        smail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smailActionPerformed(evt);
            }
        });
        in_student.add(smail);
        smail.setBounds(420, 330, 220, 28);

        idteam.setMaximumSize(new java.awt.Dimension(95, 28));
        idteam.setMinimumSize(new java.awt.Dimension(95, 25));
        idteam.setPreferredSize(new java.awt.Dimension(95, 28));
        idteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idteamActionPerformed(evt);
            }
        });
        in_student.add(idteam);
        idteam.setBounds(420, 380, 220, 28);

        dob.setPreferredSize(new java.awt.Dimension(7, 20));
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        in_student.add(dob);
        dob.setBounds(420, 160, 220, 26);

        background11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        in_student.add(background11);
        background11.setBounds(0, 0, 998, 540);

        insert_fn.add(in_student, "card2");

        team_proj_in.setLayout(null);

        projid.setBackground(new java.awt.Color(0, 0, 0));
        projid.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        projid.setForeground(new java.awt.Color(255, 255, 255));
        projid.setText("ENTER PROJECT AND TEAM DETAILS:-");
        team_proj_in.add(projid);
        projid.setBounds(330, 30, 310, 40);

        proj_id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        proj_id.setForeground(new java.awt.Color(255, 255, 255));
        proj_id.setText("Project ID :");
        team_proj_in.add(proj_id);
        proj_id.setBounds(280, 180, 120, 40);

        mail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("Project Name:");
        mail.setMaximumSize(new java.awt.Dimension(95, 25));
        mail.setMinimumSize(new java.awt.Dimension(95, 25));
        mail.setPreferredSize(new java.awt.Dimension(95, 25));
        team_proj_in.add(mail);
        mail.setBounds(280, 230, 120, 40);

        id_proj.setMaximumSize(new java.awt.Dimension(95, 28));
        id_proj.setMinimumSize(new java.awt.Dimension(95, 25));
        id_proj.setPreferredSize(new java.awt.Dimension(95, 28));
        id_proj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_projActionPerformed(evt);
            }
        });
        team_proj_in.add(id_proj);
        id_proj.setBounds(420, 190, 220, 28);

        tm_id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tm_id.setForeground(new java.awt.Color(255, 255, 255));
        tm_id.setText("Team ID:");
        team_proj_in.add(tm_id);
        tm_id.setBounds(280, 80, 120, 40);

        teachername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        teachername.setForeground(new java.awt.Color(255, 255, 255));
        teachername.setText("Team Name :");
        teachername.setMaximumSize(new java.awt.Dimension(95, 25));
        teachername.setMinimumSize(new java.awt.Dimension(95, 25));
        teachername.setPreferredSize(new java.awt.Dimension(95, 25));
        team_proj_in.add(teachername);
        teachername.setBounds(280, 130, 120, 40);

        tmid.setMaximumSize(new java.awt.Dimension(95, 28));
        tmid.setMinimumSize(new java.awt.Dimension(95, 25));
        tmid.setPreferredSize(new java.awt.Dimension(95, 28));
        tmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmidActionPerformed(evt);
            }
        });
        team_proj_in.add(tmid);
        tmid.setBounds(420, 90, 220, 28);

        tmname.setMaximumSize(new java.awt.Dimension(95, 28));
        tmname.setMinimumSize(new java.awt.Dimension(95, 25));
        tmname.setPreferredSize(new java.awt.Dimension(95, 28));
        tmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmnameActionPerformed(evt);
            }
        });
        team_proj_in.add(tmname);
        tmname.setBounds(420, 140, 220, 28);

        proj_name.setMaximumSize(new java.awt.Dimension(95, 28));
        proj_name.setMinimumSize(new java.awt.Dimension(95, 25));
        proj_name.setPreferredSize(new java.awt.Dimension(95, 28));
        proj_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proj_nameActionPerformed(evt);
            }
        });
        team_proj_in.add(proj_name);
        proj_name.setBounds(420, 240, 220, 28);

        teacher_id.setMaximumSize(new java.awt.Dimension(95, 28));
        teacher_id.setMinimumSize(new java.awt.Dimension(95, 25));
        teacher_id.setPreferredSize(new java.awt.Dimension(95, 28));
        teacher_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_idActionPerformed(evt);
            }
        });
        team_proj_in.add(teacher_id);
        teacher_id.setBounds(420, 290, 220, 28);

        teach_id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        teach_id.setForeground(new java.awt.Color(255, 255, 255));
        teach_id.setText("Teacher ID :");
        team_proj_in.add(teach_id);
        teach_id.setBounds(280, 280, 120, 40);

        reset2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        reset2.setText("RESET");
        reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2ActionPerformed(evt);
            }
        });
        team_proj_in.add(reset2);
        reset2.setBounds(530, 350, 110, 24);

        submit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enter.png"))); // NOI18N
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        team_proj_in.add(submit2);
        submit2.setBounds(400, 350, 110, 24);

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        back.setText("BACK");
        back.setMaximumSize(new java.awt.Dimension(111, 33));
        back.setMinimumSize(new java.awt.Dimension(111, 33));
        back.setPreferredSize(new java.awt.Dimension(111, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        team_proj_in.add(back);
        back.setBounds(270, 350, 110, 26);

        background2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        team_proj_in.add(background2);
        background2.setBounds(0, 0, 998, 540);

        insert_fn.add(team_proj_in, "card3");

        multiple_fn.add(insert_fn, "card2");

        view_proj.setLayout(null);

        viewproj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "Team ID", "Project ID", "Project Name", "Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        projtable.setViewportView(viewproj);
        if (viewproj.getColumnModel().getColumnCount() > 0) {
            viewproj.getColumnModel().getColumn(0).setResizable(false);
            viewproj.getColumnModel().getColumn(0).setPreferredWidth(40);
            viewproj.getColumnModel().getColumn(1).setResizable(false);
            viewproj.getColumnModel().getColumn(1).setPreferredWidth(20);
            viewproj.getColumnModel().getColumn(2).setResizable(false);
            viewproj.getColumnModel().getColumn(2).setPreferredWidth(20);
            viewproj.getColumnModel().getColumn(3).setResizable(false);
            viewproj.getColumnModel().getColumn(3).setPreferredWidth(180);
            viewproj.getColumnModel().getColumn(4).setResizable(false);
            viewproj.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        view_proj.add(projtable);
        projtable.setBounds(40, 42, 620, 240);

        background3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        view_proj.add(background3);
        background3.setBounds(0, 0, 998, 540);

        multiple_fn.add(view_proj, "card3");

        view_tm.setLayout(null);

        viewteam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team ID", "Team Name", "Project ID", "Project Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        teamtable.setViewportView(viewteam);
        if (viewteam.getColumnModel().getColumnCount() > 0) {
            viewteam.getColumnModel().getColumn(0).setPreferredWidth(20);
            viewteam.getColumnModel().getColumn(1).setPreferredWidth(30);
            viewteam.getColumnModel().getColumn(2).setPreferredWidth(20);
            viewteam.getColumnModel().getColumn(3).setPreferredWidth(180);
        }

        view_tm.add(teamtable);
        teamtable.setBounds(40, 40, 620, 240);

        background4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        view_tm.add(background4);
        background4.setBounds(0, 0, 998, 540);

        multiple_fn.add(view_tm, "card4");

        view_teacher.setLayout(null);

        teacher_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Teacher Name", "Phone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        allteacher.setViewportView(teacher_view);
        if (teacher_view.getColumnModel().getColumnCount() > 0) {
            teacher_view.getColumnModel().getColumn(0).setPreferredWidth(20);
            teacher_view.getColumnModel().getColumn(1).setPreferredWidth(30);
            teacher_view.getColumnModel().getColumn(2).setPreferredWidth(20);
            teacher_view.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        view_teacher.add(allteacher);
        allteacher.setBounds(40, 40, 620, 240);

        background1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Black_light_dark_figures_73356_1280x720.jpg"))); // NOI18N
        view_teacher.add(background1);
        background1.setBounds(0, 0, 998, 540);

        multiple_fn.add(view_teacher, "card5");

        getContentPane().add(multiple_fn);
        multiple_fn.setBounds(230, 0, 764, 540);

        date.setText("Date");
        date_time.add(date);

        time.setText("Time");
        date_time.add(time);

        setJMenuBar(date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(insert_fn);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       multiple_fn.removeAll();
        multiple_fn.add(for_options);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       
    }//GEN-LAST:event_insertActionPerformed

    private void view_projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_projectActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(view_proj);
        multiple_fn.repaint();
        multiple_fn.revalidate();        
               con=connect.ConnectDB();
       
       String s="select M.usn,T.tm_id,P.pid,P.pname,M.finalmarks\n" +
            "from team T,project P,marks M\n" +
            "where P.pid=T.pid and P.pid=M.pid";
        
       DefaultTableModel tb=(DefaultTableModel) viewproj.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[5];
         pst2=con.prepareStatement(s);
          rs1= pst2.executeQuery();
          
          if(rs1.next())
          {
              
              do
              {
                rg[0]=rs1.getString(1);
                rg[1]=rs1.getString(2);
                rg[2]=rs1.getString(3);
                rg[3]=rs1.getString(4);
                rg[4]=rs1.getString(5);
                
                tb.addRow(rg);
                
              }while(rs1.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_view_projectActionPerformed

    private void view_teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_teamActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(view_tm);
        multiple_fn.repaint();
        multiple_fn.revalidate();     
                con=connect.ConnectDB();
       
       String s="select T.tm_id,T.tm_name,P.pid,P.pname\n" +
            "from team T,project P\n" +
            "where T.pid=P.pid ";
        
       DefaultTableModel tb=(DefaultTableModel) viewteam.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[4];
         pst3=con.prepareStatement(s);
          rs2= pst3.executeQuery();
          
          if(rs2.next())
          {
              
              do
              {
                rg[0]=rs2.getString(1);
                rg[1]=rs2.getString(2);
                rg[2]=rs2.getString(3);
                rg[3]=rs2.getString(4);
               // rg[4]=rs2.getString(5);
                
                tb.addRow(rg);
                
              }while(rs2.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_view_teamActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       close();
        new Home().setVisible(true);        
    }//GEN-LAST:event_logoutActionPerformed

    private void inteamprojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inteamprojActionPerformed
        multiple_fn.removeAll();
        multiple_fn.add(team_proj_in);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       
    }//GEN-LAST:event_inteamprojActionPerformed

    private void id_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_projActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_projActionPerformed

    private void tmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmidActionPerformed

    private void tmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmnameActionPerformed

    private void proj_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proj_nameActionPerformed

    private void teacher_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_idActionPerformed

    private void reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2ActionPerformed
        id_proj.setText("");
        tmid.setText("");
        tmname.setText("");
        proj_name.setText("");
        teacher_id.setText("");      
        
    }//GEN-LAST:event_reset2ActionPerformed

    private void in_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_studActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(in_student);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       

    }//GEN-LAST:event_in_studActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(for_options);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       
      
    }//GEN-LAST:event_backActionPerformed

    private void insertKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insertKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertKeyPressed

    private void reset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset3ActionPerformed

        susn.setText("");
        sname.setText("");
        phone.setText("");
        add.setText("");
        idteam.setText("");      
        smail.setText("");
        dob.setText("");
        
       
        
    }//GEN-LAST:event_reset3ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        multiple_fn.removeAll();
        multiple_fn.add(for_options);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       
    }//GEN-LAST:event_back1ActionPerformed

    private void susnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_susnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_susnActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void smailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smailActionPerformed

    private void idteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idteamActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed
       if (susn.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student usn","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
       if (sname.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student name","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }
      if (dob.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student dob","Error", JOptionPane.ERROR_MESSAGE);
           return;
      }
      if (phone.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student phone","Error", JOptionPane.ERROR_MESSAGE);
           return;
    }
    if (add.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student address","Error", JOptionPane.ERROR_MESSAGE);
           return;
    }
    if (smail.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student mail","Error", JOptionPane.ERROR_MESSAGE);
           return;
    }
    if (idteam.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student team-id","Error", JOptionPane.ERROR_MESSAGE);
           return;
    }
    con=connect.ConnectDB();
    try{
        String sql11="Select usn from student where usn= '" + susn.getText() + "'";
        pst=con.prepareStatement(sql11);
          rs= pst.executeQuery();
          if (rs.next()){
              JOptionPane.showMessageDialog( this, "USN already exists","Error", JOptionPane.ERROR_MESSAGE);
        susn.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    try{
        String sql11="Select tm_id from team where tm_id= '" + idteam.getText() + "'";
        pst2=con.prepareStatement(sql11);
          rs2= pst2.executeQuery();
          boolean record=rs2.next();
          if (!record){
              JOptionPane.showMessageDialog( this, "Team id doesn't exists","Error", JOptionPane.ERROR_MESSAGE);
        idteam.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
      try{
            String sql1="insert into student(usn,name,dob,sphone,address,st_mail,tm_id) values(?,?,?,?,?,?,?)";
            
            pst1=con.prepareStatement(sql1);
            pst1.setString(1,susn.getText());
            pst1.setString(2,sname.getText());
            pst1.setString(3,dob.getText());
            pst1.setString(4,phone.getText());
            pst1.setString(5,add.getText());
            pst1.setString(6,smail.getText());
            pst1.setString(7,idteam.getText());
            
            pst1.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully Registered");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_submit3ActionPerformed

    private void teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersActionPerformed
       
        multiple_fn.removeAll();
        multiple_fn.add(view_teacher);
        multiple_fn.repaint();
        multiple_fn.revalidate();   
       
        con=connect.ConnectDB();
       
       String s="select teacher_id,tname,tphone,t_mail\n" +
            "from teacher\n";
        
       DefaultTableModel tb=(DefaultTableModel) teacher_view.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[4];
         pst8=con.prepareStatement(s);
          rs8= pst8.executeQuery();
          
          if(rs8.next())
          {
              
              do
              {
                rg[0]=rs8.getString(1);
                rg[1]=rs8.getString(2);
                rg[2]=rs8.getString(3);
                rg[3]=rs8.getString(4);
                
                tb.addRow(rg);
                
              }while(rs8.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_teachersActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
       if (tmid.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter teacher id","Error", JOptionPane.ERROR_MESSAGE);
           return;
       } 
      if (tmname.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter teacher name","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (id_proj.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student usn","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (proj_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student usn","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (teacher_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter student usn","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
        con=connect.ConnectDB();
        
        try{
        String sql11="Select tm_id from team where tm_id= '" + tmid.getText() + "'";
        pst4=con.prepareStatement(sql11);
          rs3= pst4.executeQuery();
          if (rs3.next()){
              JOptionPane.showMessageDialog( this, "team id already exists","Error", JOptionPane.ERROR_MESSAGE);
        tmid.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
        try{
        String sql11="Select pid from project where pid= '" + id_proj.getText() + "'";
        pst5=con.prepareStatement(sql11);
          rs4= pst5.executeQuery();
          if (rs4.next()){
              JOptionPane.showMessageDialog( this, "project id already exists","Error", JOptionPane.ERROR_MESSAGE);
       id_proj.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
        try{
        String sql11="Select teacher_id from teacher where teacher_id= '" + teacher_id.getText() + "'";
        pst2=con.prepareStatement(sql11);
          rs2= pst2.executeQuery();
          boolean record=rs2.next();
          if (!record){
              JOptionPane.showMessageDialog( this, "Teacher id doesn't exists","Error", JOptionPane.ERROR_MESSAGE);
        teacher_id.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
        try{
            String sql1="insert into team(tm_id,tm_name,pid,teacher_id) values(?,?,?,?)";
            String sql2="insert into project(pid,pname) values(?,?)";
            
            pst6=con.prepareStatement(sql1);
            pst6.setString(1,tmid.getText());
            pst6.setString(2,tmname.getText());
            pst6.setString(3,id_proj.getText());
            pst6.setString(4,teacher_id.getText());
            pst6.execute();
            
            pst7=con.prepareStatement(sql2);
            pst7.setString(1,id_proj.getText());
            pst7.setString(2,proj_name.getText());
            pst7.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully Registered");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
        
    }//GEN-LAST:event_submit2ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_fn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextArea add;
    private javax.swing.JLabel address;
    private javax.swing.JScrollPane allteacher;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background11;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JMenu date;
    private javax.swing.JMenuBar date_time;
    private javax.swing.JTextField dob;
    private javax.swing.JPanel for_options;
    private javax.swing.JTextField id_proj;
    private javax.swing.JTextField idteam;
    private javax.swing.JButton in_stud;
    private javax.swing.JPanel in_student;
    private javax.swing.JButton insert;
    private javax.swing.JPanel insert_fn;
    private javax.swing.JButton inteamproj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mail1;
    private javax.swing.JPanel multiple_fn;
    private javax.swing.JLabel name;
    private javax.swing.JPanel options;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel proj_id;
    private javax.swing.JTextField proj_name;
    private javax.swing.JLabel projid;
    private javax.swing.JLabel projid2;
    private javax.swing.JScrollPane projtable;
    private javax.swing.JButton reset2;
    private javax.swing.JButton reset3;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField smail;
    private javax.swing.JTextField sname;
    private javax.swing.JLabel sphone;
    private javax.swing.JButton submit2;
    private javax.swing.JButton submit3;
    private javax.swing.JTextField susn;
    private javax.swing.JLabel teach_id;
    private javax.swing.JTextField teacher_id;
    private javax.swing.JTable teacher_view;
    private javax.swing.JLabel teachername;
    private javax.swing.JButton teachers;
    private javax.swing.JLabel team_id;
    private javax.swing.JPanel team_proj_in;
    private javax.swing.JScrollPane teamtable;
    private javax.swing.JMenu time;
    private javax.swing.JLabel tm_id;
    private javax.swing.JTextField tmid;
    private javax.swing.JTextField tmname;
    private javax.swing.JLabel usn;
    private javax.swing.JPanel view_proj;
    private javax.swing.JButton view_project;
    private javax.swing.JPanel view_teacher;
    private javax.swing.JButton view_team;
    private javax.swing.JPanel view_tm;
    private javax.swing.JTable viewproj;
    private javax.swing.JTable viewteam;
    // End of variables declaration//GEN-END:variables
}
