import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class Home extends javax.swing.JFrame  {

       Connection con=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;
    ResultSet rs5=null;
     ResultSet rs6=null;
      ResultSet rs7=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
     PreparedStatement pst2=null;
     PreparedStatement pst3=null;
     PreparedStatement pst4=null;
     PreparedStatement pst5=null;
     PreparedStatement pst6=null;
     PreparedStatement pst7=null;
    public Home() {
        initComponents();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        GregorianCalendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(+day+"/"+(month+1)+"/"+year);
        int hour=cal.get(Calendar.AM_PM);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time.setText(+hour+":"+minute+":"+second);
        multiple_logins.removeAll();
    }
 
    public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        admin = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        userr = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();
        multiple_logins = new javax.swing.JPanel();
        admin_login = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        inUser = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        inPass = new javax.swing.JPasswordField();
        inLogin = new javax.swing.JButton();
        inReset = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        teacher_login = new javax.swing.JPanel();
        user1 = new javax.swing.JLabel();
        inUser1 = new javax.swing.JTextField();
        password1 = new javax.swing.JLabel();
        inPass1 = new javax.swing.JPasswordField();
        inLogin1 = new javax.swing.JButton();
        inReset1 = new javax.swing.JButton();
        register = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        user_show = new javax.swing.JPanel();
        projid = new javax.swing.JLabel();
        usn = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        pidtable = new javax.swing.JScrollPane();
        outputtable = new javax.swing.JTable();
        background3 = new javax.swing.JLabel();
        teacher_register = new javax.swing.JPanel();
        user2 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        inReset2 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        tphone = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        t_phone = new javax.swing.JTextField();
        teacherid = new javax.swing.JLabel();
        teachername = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_mail = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        date_time = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 540));
        setPreferredSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(51, 51, 51));

        admin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png"))); // NOI18N
        admin.setText("ADMIN");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        teacher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/teaching (1).png"))); // NOI18N
        teacher.setText("TEACHER");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });

        userr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/users (1).png"))); // NOI18N
        userr.setText("USER");
        userr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userrActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by (1).png"))); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(userr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 190, 540);

        separator.setBackground(new java.awt.Color(240, 240, 240));
        separator.setForeground(new java.awt.Color(240, 240, 240));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(190, 0, 2, 520);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/загружено-1.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1322, 844);

        multiple_logins.setLayout(new java.awt.CardLayout());

        admin_login.setLayout(null);

        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username :");
        admin_login.add(user);
        user.setBounds(190, 270, 120, 40);

        inUser.setMaximumSize(new java.awt.Dimension(95, 25));
        inUser.setMinimumSize(new java.awt.Dimension(95, 25));
        inUser.setPreferredSize(new java.awt.Dimension(95, 25));
        admin_login.add(inUser);
        inUser.setBounds(330, 280, 150, 26);

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password :");
        password.setMaximumSize(new java.awt.Dimension(95, 25));
        password.setMinimumSize(new java.awt.Dimension(95, 25));
        password.setPreferredSize(new java.awt.Dimension(95, 25));
        admin_login.add(password);
        password.setBounds(190, 320, 120, 40);

        inPass.setMaximumSize(new java.awt.Dimension(95, 25));
        inPass.setMinimumSize(new java.awt.Dimension(95, 25));
        inPass.setPreferredSize(new java.awt.Dimension(95, 25));
        admin_login.add(inPass);
        inPass.setBounds(330, 330, 150, 26);

        inLogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        inLogin.setText("LOGIN");
        inLogin.setMaximumSize(new java.awt.Dimension(111, 33));
        inLogin.setMinimumSize(new java.awt.Dimension(111, 33));
        inLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLoginActionPerformed(evt);
            }
        });
        admin_login.add(inLogin);
        inLogin.setBounds(250, 380, 100, 25);

        inReset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        inReset.setText("RESET");
        inReset.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inResetActionPerformed(evt);
            }
        });
        admin_login.add(inReset);
        inReset.setBounds(380, 380, 100, 25);

        background1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/загружено-1.jpg"))); // NOI18N
        admin_login.add(background1);
        background1.setBounds(0, 0, 1322, 844);

        multiple_logins.add(admin_login, "card2");

        teacher_login.setLayout(null);

        user1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setText("Username :");
        teacher_login.add(user1);
        user1.setBounds(190, 270, 120, 40);

        inUser1.setMaximumSize(new java.awt.Dimension(95, 25));
        inUser1.setMinimumSize(new java.awt.Dimension(95, 25));
        inUser1.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_login.add(inUser1);
        inUser1.setBounds(330, 280, 150, 26);

        password1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 255));
        password1.setText("Password :");
        password1.setMaximumSize(new java.awt.Dimension(95, 25));
        password1.setMinimumSize(new java.awt.Dimension(95, 25));
        password1.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_login.add(password1);
        password1.setBounds(190, 320, 120, 40);

        inPass1.setMaximumSize(new java.awt.Dimension(95, 25));
        inPass1.setMinimumSize(new java.awt.Dimension(95, 25));
        inPass1.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_login.add(inPass1);
        inPass1.setBounds(330, 330, 150, 26);

        inLogin1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        inLogin1.setText("LOGIN");
        inLogin1.setMaximumSize(new java.awt.Dimension(111, 33));
        inLogin1.setMinimumSize(new java.awt.Dimension(111, 33));
        inLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLogin1ActionPerformed(evt);
            }
        });
        teacher_login.add(inLogin1);
        inLogin1.setBounds(180, 390, 110, 26);

        inReset1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        inReset1.setText("RESET");
        inReset1.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset1.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset1ActionPerformed(evt);
            }
        });
        teacher_login.add(inReset1);
        inReset1.setBounds(430, 390, 100, 26);

        register.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add-a-contact-on-phone-interface-symbol-of-a-user-with-a-plus-sign.png"))); // NOI18N
        register.setText("REGISTER");
        register.setMaximumSize(new java.awt.Dimension(111, 33));
        register.setMinimumSize(new java.awt.Dimension(111, 33));
        register.setPreferredSize(new java.awt.Dimension(111, 33));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        teacher_login.add(register);
        register.setBounds(300, 390, 120, 26);

        background2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/загружено-1.jpg"))); // NOI18N
        teacher_login.add(background2);
        background2.setBounds(0, 0, 1322, 844);

        multiple_logins.add(teacher_login, "card3");

        user_show.setLayout(null);

        projid.setBackground(new java.awt.Color(0, 0, 0));
        projid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        projid.setForeground(new java.awt.Color(255, 255, 255));
        projid.setText("ENTER USN TO VIEW MARKS:-");
        user_show.add(projid);
        projid.setBounds(430, 40, 310, 40);
        user_show.add(usn);
        usn.setBounds(430, 80, 120, 26);

        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        user_show.add(search);
        search.setBounds(580, 80, 110, 24);

        outputtable.setBackground(new java.awt.Color(51, 51, 51));
        outputtable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        outputtable.setForeground(new java.awt.Color(255, 255, 255));
        outputtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "Project ID", "Team ID", "Teacher ID", "Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outputtable.setColumnSelectionAllowed(true);
        outputtable.setGridColor(new java.awt.Color(102, 102, 102));
        outputtable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        outputtable.setSelectionForeground(new java.awt.Color(102, 102, 102));
        pidtable.setViewportView(outputtable);
        outputtable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (outputtable.getColumnModel().getColumnCount() > 0) {
            outputtable.getColumnModel().getColumn(0).setResizable(false);
            outputtable.getColumnModel().getColumn(1).setResizable(false);
            outputtable.getColumnModel().getColumn(2).setResizable(false);
        }

        user_show.add(pidtable);
        pidtable.setBounds(40, 160, 640, 200);

        background3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/загружено-1.jpg"))); // NOI18N
        user_show.add(background3);
        background3.setBounds(0, 0, 1322, 844);

        multiple_logins.add(user_show, "card4");

        teacher_register.setLayout(null);

        user2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setText("Username :");
        teacher_register.add(user2);
        user2.setBounds(380, 240, 120, 40);

        password2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setText("Password :");
        password2.setMaximumSize(new java.awt.Dimension(95, 25));
        password2.setMinimumSize(new java.awt.Dimension(95, 25));
        password2.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_register.add(password2);
        password2.setBounds(380, 290, 120, 40);

        pass.setMaximumSize(new java.awt.Dimension(95, 25));
        pass.setMinimumSize(new java.awt.Dimension(95, 25));
        pass.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_register.add(pass);
        pass.setBounds(520, 300, 150, 26);

        username.setMaximumSize(new java.awt.Dimension(95, 25));
        username.setMinimumSize(new java.awt.Dimension(95, 25));
        username.setPreferredSize(new java.awt.Dimension(95, 25));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        teacher_register.add(username);
        username.setBounds(520, 250, 150, 26);

        inReset2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        inReset2.setText("RESET");
        inReset2.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset2.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset2ActionPerformed(evt);
            }
        });
        teacher_register.add(inReset2);
        inReset2.setBounds(560, 360, 110, 26);

        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enter.png"))); // NOI18N
        submit.setText("SUBMIT");
        submit.setMaximumSize(new java.awt.Dimension(111, 33));
        submit.setMinimumSize(new java.awt.Dimension(111, 33));
        submit.setPreferredSize(new java.awt.Dimension(111, 33));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        teacher_register.add(submit);
        submit.setBounds(430, 360, 110, 26);

        tphone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tphone.setForeground(new java.awt.Color(255, 255, 255));
        tphone.setText("Phone No. :");
        teacher_register.add(tphone);
        tphone.setBounds(380, 140, 120, 40);

        mail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("E-mail :");
        mail.setMaximumSize(new java.awt.Dimension(95, 25));
        mail.setMinimumSize(new java.awt.Dimension(95, 25));
        mail.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_register.add(mail);
        mail.setBounds(380, 190, 120, 40);

        t_phone.setMaximumSize(new java.awt.Dimension(95, 25));
        t_phone.setMinimumSize(new java.awt.Dimension(95, 25));
        t_phone.setPreferredSize(new java.awt.Dimension(95, 25));
        t_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_phoneActionPerformed(evt);
            }
        });
        teacher_register.add(t_phone);
        t_phone.setBounds(520, 150, 150, 26);

        teacherid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teacherid.setForeground(new java.awt.Color(255, 255, 255));
        teacherid.setText("Teacher ID :");
        teacher_register.add(teacherid);
        teacherid.setBounds(380, 40, 120, 40);

        teachername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teachername.setForeground(new java.awt.Color(255, 255, 255));
        teachername.setText("Name :");
        teachername.setMaximumSize(new java.awt.Dimension(95, 25));
        teachername.setMinimumSize(new java.awt.Dimension(95, 25));
        teachername.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_register.add(teachername);
        teachername.setBounds(380, 90, 120, 40);

        t_id.setMaximumSize(new java.awt.Dimension(95, 25));
        t_id.setMinimumSize(new java.awt.Dimension(95, 25));
        t_id.setPreferredSize(new java.awt.Dimension(95, 25));
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        teacher_register.add(t_id);
        t_id.setBounds(520, 50, 150, 26);

        t_name.setMaximumSize(new java.awt.Dimension(95, 25));
        t_name.setMinimumSize(new java.awt.Dimension(95, 25));
        t_name.setPreferredSize(new java.awt.Dimension(95, 25));
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        teacher_register.add(t_name);
        t_name.setBounds(520, 100, 150, 26);

        t_mail.setMaximumSize(new java.awt.Dimension(95, 25));
        t_mail.setMinimumSize(new java.awt.Dimension(95, 25));
        t_mail.setPreferredSize(new java.awt.Dimension(95, 25));
        t_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_mailActionPerformed(evt);
            }
        });
        teacher_register.add(t_mail);
        t_mail.setBounds(520, 200, 150, 26);

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        back.setText("BACK");
        back.setMaximumSize(new java.awt.Dimension(111, 33));
        back.setMinimumSize(new java.awt.Dimension(111, 33));
        back.setPreferredSize(new java.awt.Dimension(111, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        teacher_register.add(back);
        back.setBounds(300, 360, 110, 26);

        background4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/загружено-1.jpg"))); // NOI18N
        teacher_register.add(background4);
        background4.setBounds(0, 0, 1322, 844);

        multiple_logins.add(teacher_register, "card5");

        getContentPane().add(multiple_logins);
        multiple_logins.setBounds(196, 0, 730, 540);

        date.setText("Date");
        date_time.add(date);

        time.setText("Time");
        date_time.add(time);

        setJMenuBar(date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void inLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLoginActionPerformed
         if(inUser.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Username Missing", "Error Message", JOptionPane.WARNING_MESSAGE);
        }
        if(inPass.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Password Missing", "Error Message", JOptionPane.WARNING_MESSAGE);
        }
        if(inUser.getText().equals("admin") && inPass.getText().equals("admin"))
        {
        JOptionPane.showMessageDialog(this, "LOGIN SUCESSFULL");    
        close();
        new Admin_fn().setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(this, "LOGIN UNSUCESSFULL");
    }//GEN-LAST:event_inLoginActionPerformed

    private void inResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inResetActionPerformed

        inUser.setText("");
        inPass.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_inResetActionPerformed

    private void inLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLogin1ActionPerformed
if (inUser1.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    String Password= String.valueOf(inPass1.getPassword());
        if (Password.equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter password","Error", JOptionPane.ERROR_MESSAGE);
           return;
          
            }
        con=connect.ConnectDB();
        String sql= "select * from userdetails where user_name= '" + inUser1.getText() + "' and password ='" + inPass1.getText() + "'";
        try {
       pst5=con.prepareStatement(sql);
          rs5= pst5.executeQuery();
          if (rs5.next()){
             this.hide();
             new Teacher_fn().setVisible(true);
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrong Username or Password!","Access denied",JOptionPane.ERROR_MESSAGE);
          }
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }    
    }//GEN-LAST:event_inLogin1ActionPerformed

    private void inReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset1ActionPerformed
        inUser1.setText("");
        inPass1.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_inReset1ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        
        multiple_logins.removeAll();
        multiple_logins.add(admin_login);
        multiple_logins.repaint();
        multiple_logins.revalidate(); 
        inUser.setText("");
        inPass.setText("");

    }//GEN-LAST:event_adminActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
    
        multiple_logins.removeAll();
        multiple_logins.add(teacher_login);
        multiple_logins.repaint();
        multiple_logins.revalidate();      
         inUser1.setText("");
        inPass1.setText("");

    }//GEN-LAST:event_teacherActionPerformed

    private void userrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userrActionPerformed
multiple_logins.removeAll();
multiple_logins.add(user_show);
multiple_logins.repaint();
multiple_logins.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_userrActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

multiple_logins.removeAll();
multiple_logins.add(teacher_register);
multiple_logins.repaint();
multiple_logins.revalidate();       

        
    }//GEN-LAST:event_registerActionPerformed

    private void inReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset2ActionPerformed
        username.setText("");
        pass.setText("");
        t_id.setText("");
        t_name.setText("");
        t_mail.setText("");
        t_phone.setText("");
       
    }//GEN-LAST:event_inReset2ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
      if (t_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Teacher id","Error", JOptionPane.ERROR_MESSAGE);
           return;
       } 
      if (t_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Teacher name","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (t_phone.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Teacher phone","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (t_mail.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Teacher E-mail","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (username.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Username","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      if (pass.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Password","Error", JOptionPane.ERROR_MESSAGE);
           return;
       }  
      
      con=connect.ConnectDB();
    try{
        String sql11="Select teacher_id from teacher where teacher_id= '" + t_id.getText() + "'";
        pst=con.prepareStatement(sql11);
          rs= pst.executeQuery();
          if (rs.next()){
              JOptionPane.showMessageDialog( this, "Teacher id already exists","Error", JOptionPane.ERROR_MESSAGE);
        t_id.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    try{
        String sql11="Select user_name from userdetails where user_name= '" + username.getText() + "'";
        pst=con.prepareStatement(sql11);
          rs= pst.executeQuery();
          if (rs.next()){
              JOptionPane.showMessageDialog( this, "Username already exists","Error", JOptionPane.ERROR_MESSAGE);
        username.setText("");
        
       return;
          }
        }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    try{
            String sql1="insert into teacher(teacher_id,tname,tphone,t_mail) values(?,?,?,?)";
            String sql2="insert into userdetails(user_name,password) values(?,?)";
            
            pst1=con.prepareStatement(sql1);
            pst1.setString(1,t_id.getText());
            pst1.setString(2,t_name.getText());
            pst1.setString(3,t_phone.getText());
            pst1.setString(4,t_mail.getText());
            pst1.execute();
            
            pst2=con.prepareStatement(sql2);
            pst2.setString(1,username.getText());
            pst2.setString(2,pass.getText());
            pst2.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully Registered");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    username.setText("");
        pass.setText("");
        t_id.setText("");
        t_name.setText("");
        t_mail.setText("");
        t_phone.setText("");
    }//GEN-LAST:event_submitActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void t_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_phoneActionPerformed

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mailActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    if (usn.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter USN","Error", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    con=connect.ConnectDB();
    String sql22="select usn from marks where usn='"+usn.getText()+"'";
    try {
       pst6=con.prepareStatement(sql22);
          rs6= pst6.executeQuery();
          if (rs6.next()){
              
            String sql11="select M.usn,M.pid,T.tm_id,M.teacher_id,M.finalmarks from\n"
                    + "project P,team T,marks M\n"
                    + "where P.pid=M.pid and P.pid=T.pid and M.usn='"+usn.getText()+"'";
            DefaultTableModel tb=(DefaultTableModel) outputtable.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[5];
         pst7=con.prepareStatement(sql11);
          rs7= pst7.executeQuery();
          
          if(rs7.next())
          {
              
              do
              {
                rg[0]=rs7.getString(1);
                rg[1]=rs7.getString(2);
                rg[2]=rs7.getString(3);
                rg[3]=rs7.getString(4);
                rg[4]=rs7.getString(5);
                
                tb.addRow(rg);
                
              }while(rs7.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
              
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrong USN","Denied",JOptionPane.ERROR_MESSAGE);
            usn.setText("");
       
          }
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(teacher_login);
        multiple_logins.repaint();
        multiple_logins.revalidate();      
        inUser1.setText("");
        inPass1.setText("");
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton admin;
    private javax.swing.JPanel admin_login;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JMenu date;
    private javax.swing.JMenuBar date_time;
    private javax.swing.JButton inLogin;
    private javax.swing.JButton inLogin1;
    private javax.swing.JPasswordField inPass;
    private javax.swing.JPasswordField inPass1;
    private javax.swing.JButton inReset;
    private javax.swing.JButton inReset1;
    private javax.swing.JButton inReset2;
    private javax.swing.JTextField inUser;
    private javax.swing.JTextField inUser1;
    private javax.swing.JLabel mail;
    private javax.swing.JPanel multiple_logins;
    private javax.swing.JPanel options;
    private javax.swing.JTable outputtable;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel password2;
    private javax.swing.JScrollPane pidtable;
    private javax.swing.JLabel projid;
    private javax.swing.JButton register;
    private javax.swing.JButton search;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton submit;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_mail;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_phone;
    private javax.swing.JButton teacher;
    private javax.swing.JPanel teacher_login;
    private javax.swing.JPanel teacher_register;
    private javax.swing.JLabel teacherid;
    private javax.swing.JLabel teachername;
    private javax.swing.JMenu time;
    private javax.swing.JLabel tphone;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JPanel user_show;
    private javax.swing.JTextField username;
    private javax.swing.JButton userr;
    private javax.swing.JTextField usn;
    // End of variables declaration//GEN-END:variables
}
