
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class Teacher_fn extends javax.swing.JFrame {
Connection con=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    ResultSet rs4=null;
    ResultSet rs5=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
     PreparedStatement pst2=null;
     PreparedStatement pst3=null;
     PreparedStatement pst4=null;
     PreparedStatement pst5=null;
    public Teacher_fn() {
        initComponents();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        GregorianCalendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(+day+"/"+(month+1)+"/"+year);
        int hour=cal.get(Calendar.AM_PM);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time.setText(+hour+":"+minute+":"+second);
     multiple_fn.removeAll();
    }
public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        marks_in = new javax.swing.JButton();
        proj_all = new javax.swing.JButton();
        proj_wth_marks = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        multiple_fn = new javax.swing.JPanel();
        insert_fn = new javax.swing.JPanel();
        projid = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        marks3 = new javax.swing.JTextField();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        marks1 = new javax.swing.JTextField();
        marks2 = new javax.swing.JTextField();
        p_id = new javax.swing.JTextField();
        teacher_id = new javax.swing.JTextField();
        teach_id = new javax.swing.JLabel();
        reset2 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        user2 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        username2 = new javax.swing.JTextField();
        usn = new javax.swing.JTextField();
        usn1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        ALL_PROJ = new javax.swing.JPanel();
        projtable = new javax.swing.JScrollPane();
        viewproj = new javax.swing.JTable();
        idteacher = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        TID = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        assigned_projs = new javax.swing.JPanel();
        teamtable = new javax.swing.JScrollPane();
        viewteam = new javax.swing.JTable();
        search1 = new javax.swing.JButton();
        idteacher1 = new javax.swing.JTextField();
        TID1 = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();
        date_time = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(51, 51, 51));

        marks_in.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        marks_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/spreadsheet.png"))); // NOI18N
        marks_in.setText("EVALUATE");
        marks_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_inActionPerformed(evt);
            }
        });
        marks_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marks_inKeyPressed(evt);
            }
        });

        proj_all.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        proj_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/augmented-reality (1).png"))); // NOI18N
        proj_all.setText("ALL PROJECTS");
        proj_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proj_allActionPerformed(evt);
            }
        });

        proj_wth_marks.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        proj_wth_marks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/augmented-reality.png"))); // NOI18N
        proj_wth_marks.setText("ASSIGNED");
        proj_wth_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proj_wth_marksActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by (1).png"))); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(proj_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marks_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proj_wth_marks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(marks_in, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(proj_all, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(proj_wth_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 228, 540);

        background.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background-2385902_960_720.jpg"))); // NOI18N
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background);
        background.setBounds(0, 0, 998, 540);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(226, 0, 2, 540);

        multiple_fn.setPreferredSize(new java.awt.Dimension(600, 540));
        multiple_fn.setLayout(new java.awt.CardLayout());

        insert_fn.setLayout(null);

        projid.setBackground(new java.awt.Color(0, 0, 0));
        projid.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        projid.setForeground(new java.awt.Color(255, 255, 255));
        projid.setText("ENTER PROJECT AND TEAM DETAILS :-");
        insert_fn.add(projid);
        projid.setBounds(320, 30, 320, 40);

        m3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setText("Marks3 :");
        insert_fn.add(m3);
        m3.setBounds(280, 190, 120, 40);

        pid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 255));
        pid.setText("Project ID :");
        pid.setMaximumSize(new java.awt.Dimension(95, 25));
        pid.setMinimumSize(new java.awt.Dimension(95, 25));
        pid.setPreferredSize(new java.awt.Dimension(95, 25));
        insert_fn.add(pid);
        pid.setBounds(280, 230, 120, 40);

        marks3.setMaximumSize(new java.awt.Dimension(95, 25));
        marks3.setMinimumSize(new java.awt.Dimension(95, 25));
        marks3.setPreferredSize(new java.awt.Dimension(95, 25));
        marks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks3ActionPerformed(evt);
            }
        });
        insert_fn.add(marks3);
        marks3.setBounds(420, 200, 220, 26);

        m1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("Marks1 :");
        insert_fn.add(m1);
        m1.setBounds(280, 110, 120, 40);

        m2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setText("Marks2 :");
        m2.setMaximumSize(new java.awt.Dimension(95, 25));
        m2.setMinimumSize(new java.awt.Dimension(95, 25));
        m2.setPreferredSize(new java.awt.Dimension(95, 25));
        insert_fn.add(m2);
        m2.setBounds(280, 150, 120, 40);

        marks1.setMaximumSize(new java.awt.Dimension(95, 25));
        marks1.setMinimumSize(new java.awt.Dimension(95, 25));
        marks1.setPreferredSize(new java.awt.Dimension(95, 25));
        marks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks1ActionPerformed(evt);
            }
        });
        insert_fn.add(marks1);
        marks1.setBounds(420, 120, 220, 26);

        marks2.setMaximumSize(new java.awt.Dimension(95, 25));
        marks2.setMinimumSize(new java.awt.Dimension(95, 25));
        marks2.setPreferredSize(new java.awt.Dimension(95, 25));
        marks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks2ActionPerformed(evt);
            }
        });
        insert_fn.add(marks2);
        marks2.setBounds(420, 160, 220, 26);

        p_id.setMaximumSize(new java.awt.Dimension(95, 25));
        p_id.setMinimumSize(new java.awt.Dimension(95, 25));
        p_id.setPreferredSize(new java.awt.Dimension(95, 25));
        p_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_idActionPerformed(evt);
            }
        });
        insert_fn.add(p_id);
        p_id.setBounds(420, 240, 220, 26);

        teacher_id.setMaximumSize(new java.awt.Dimension(95, 25));
        teacher_id.setMinimumSize(new java.awt.Dimension(95, 25));
        teacher_id.setPreferredSize(new java.awt.Dimension(95, 25));
        teacher_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_idActionPerformed(evt);
            }
        });
        insert_fn.add(teacher_id);
        teacher_id.setBounds(420, 280, 220, 26);

        teach_id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        teach_id.setForeground(new java.awt.Color(255, 255, 255));
        teach_id.setText("Teacher ID :");
        insert_fn.add(teach_id);
        teach_id.setBounds(280, 270, 120, 40);

        reset2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stand-by.png"))); // NOI18N
        reset2.setText("RESET");
        reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2ActionPerformed(evt);
            }
        });
        insert_fn.add(reset2);
        reset2.setBounds(530, 410, 110, 24);

        submit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enter.png"))); // NOI18N
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        insert_fn.add(submit2);
        submit2.setBounds(400, 410, 110, 24);

        user2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setText("Username :");
        insert_fn.add(user2);
        user2.setBounds(280, 310, 120, 40);

        password2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setText("Password :");
        password2.setMaximumSize(new java.awt.Dimension(95, 25));
        password2.setMinimumSize(new java.awt.Dimension(95, 25));
        password2.setPreferredSize(new java.awt.Dimension(95, 25));
        insert_fn.add(password2);
        password2.setBounds(280, 350, 120, 40);

        pass.setMaximumSize(new java.awt.Dimension(95, 25));
        pass.setMinimumSize(new java.awt.Dimension(95, 25));
        pass.setPreferredSize(new java.awt.Dimension(95, 25));
        insert_fn.add(pass);
        pass.setBounds(420, 360, 220, 26);

        username2.setMaximumSize(new java.awt.Dimension(95, 30));
        username2.setMinimumSize(new java.awt.Dimension(95, 25));
        username2.setPreferredSize(new java.awt.Dimension(95, 30));
        username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username2ActionPerformed(evt);
            }
        });
        insert_fn.add(username2);
        username2.setBounds(420, 320, 220, 26);

        usn.setMaximumSize(new java.awt.Dimension(95, 30));
        usn.setMinimumSize(new java.awt.Dimension(95, 25));
        usn.setPreferredSize(new java.awt.Dimension(95, 30));
        usn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usnActionPerformed(evt);
            }
        });
        insert_fn.add(usn);
        usn.setBounds(420, 80, 220, 26);

        usn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usn1.setForeground(new java.awt.Color(255, 255, 255));
        usn1.setText("USN :");
        insert_fn.add(usn1);
        usn1.setBounds(280, 70, 120, 40);

        background1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background-2385902_960_720.jpg"))); // NOI18N
        background1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        insert_fn.add(background1);
        background1.setBounds(0, 0, 998, 540);

        multiple_fn.add(insert_fn, "card2");

        ALL_PROJ.setLayout(null);

        viewproj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team ID", "Team Name", "Project ID", "Project Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        projtable.setViewportView(viewproj);
        if (viewproj.getColumnModel().getColumnCount() > 0) {
            viewproj.getColumnModel().getColumn(0).setPreferredWidth(20);
            viewproj.getColumnModel().getColumn(1).setPreferredWidth(30);
            viewproj.getColumnModel().getColumn(2).setPreferredWidth(20);
            viewproj.getColumnModel().getColumn(3).setPreferredWidth(180);
        }

        ALL_PROJ.add(projtable);
        projtable.setBounds(30, 120, 620, 310);
        ALL_PROJ.add(idteacher);
        idteacher.setBounds(380, 70, 120, 26);

        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        ALL_PROJ.add(search);
        search.setBounds(530, 70, 110, 24);

        TID.setBackground(new java.awt.Color(0, 0, 0));
        TID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TID.setForeground(new java.awt.Color(255, 255, 255));
        TID.setText("ENTER TEACHER ID TO VIEW :-");
        ALL_PROJ.add(TID);
        TID.setBounds(420, 20, 310, 40);

        background2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background-2385902_960_720.jpg"))); // NOI18N
        background2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ALL_PROJ.add(background2);
        background2.setBounds(0, 0, 998, 540);

        multiple_fn.add(ALL_PROJ, "card3");

        assigned_projs.setLayout(null);

        viewteam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team ID", "USN", "Project ID", "Project Name", "Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        teamtable.setViewportView(viewteam);
        if (viewteam.getColumnModel().getColumnCount() > 0) {
            viewteam.getColumnModel().getColumn(0).setPreferredWidth(20);
            viewteam.getColumnModel().getColumn(1).setPreferredWidth(30);
            viewteam.getColumnModel().getColumn(2).setPreferredWidth(20);
            viewteam.getColumnModel().getColumn(3).setPreferredWidth(180);
            viewteam.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        assigned_projs.add(teamtable);
        teamtable.setBounds(30, 120, 620, 330);

        search1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        search1.setText("SEARCH");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        assigned_projs.add(search1);
        search1.setBounds(530, 70, 110, 24);
        assigned_projs.add(idteacher1);
        idteacher1.setBounds(380, 70, 120, 26);

        TID1.setBackground(new java.awt.Color(0, 0, 0));
        TID1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TID1.setForeground(new java.awt.Color(255, 255, 255));
        TID1.setText("ENTER TEACHER ID TO VIEW :-");
        assigned_projs.add(TID1);
        TID1.setBounds(420, 20, 310, 40);

        background5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background-2385902_960_720.jpg"))); // NOI18N
        background5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        assigned_projs.add(background5);
        background5.setBounds(0, 0, 998, 540);

        multiple_fn.add(assigned_projs, "card4");

        getContentPane().add(multiple_fn);
        multiple_fn.setBounds(230, 0, 764, 540);

        date.setText("Date");
        date_time.add(date);

        time.setText("Time");
        date_time.add(time);

        setJMenuBar(date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marks_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_inActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(insert_fn);
        multiple_fn.repaint();
        multiple_fn.revalidate();
               
    }//GEN-LAST:event_marks_inActionPerformed

    private void marks_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marks_inKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks_inKeyPressed

    private void proj_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_allActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(ALL_PROJ);
        multiple_fn.repaint();
        multiple_fn.revalidate();
    }//GEN-LAST:event_proj_allActionPerformed

    private void proj_wth_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_wth_marksActionPerformed

        multiple_fn.removeAll();
        multiple_fn.add(assigned_projs);
        multiple_fn.repaint();
        multiple_fn.revalidate();
    }//GEN-LAST:event_proj_wth_marksActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void marks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks3ActionPerformed

    private void marks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks1ActionPerformed

    private void marks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks2ActionPerformed

    private void p_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_idActionPerformed

    private void teacher_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_idActionPerformed

    private void reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2ActionPerformed
        marks3.setText("");
        marks1.setText("");
        marks2.setText("");
        username2.setText("");
        p_id.setText("");
        pass.setText("");
        teacher_id.setText("");
        usn.setText("");
    }//GEN-LAST:event_reset2ActionPerformed

    private void username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if (idteacher.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter teacher id","Error", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    con=connect.ConnectDB();
    String sql="select teacher_id from team where teacher_id='"+idteacher.getText()+"'";
    try {
       pst2=con.prepareStatement(sql);
          rs2= pst2.executeQuery();
          if (rs2.next()){
              
            String sql1="select S.usn,Tm.tm_id,Tm.pid,P.pname from\n"
                    + "project P,team Tm,teacher T,student S\n"
                    + "where S.tm_id=Tm.tm_id and P.pid=Tm.pid and Tm.teacher_id=T.teacher_id and T.teacher_id='"+idteacher.getText()+"'";
            DefaultTableModel tb=(DefaultTableModel) viewproj.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[4];
         pst3=con.prepareStatement(sql1);
          rs3= pst3.executeQuery();
          
          if(rs3.next())
          {
              
              do
              {
                rg[0]=rs3.getString(1);
                rg[1]=rs3.getString(2);
                rg[2]=rs3.getString(3);
                rg[3]=rs3.getString(4);
                
                tb.addRow(rg);
                
              }while(rs3.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
              
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrond Teacher Id","Denied",JOptionPane.ERROR_MESSAGE);
          }
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    }//GEN-LAST:event_searchActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed

        if (idteacher1.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter teacher id","Error", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    con=connect.ConnectDB();
    String sql="select teacher_id from team where teacher_id='"+idteacher1.getText()+"'";
    try {
        //CallableStatement cs;
        //cs=con.prepareCall("{ call fmarks}");
             //cs.executeUpdate();
       pst4=con.prepareStatement(sql);
          rs4= pst4.executeQuery();
          if (rs4.next()){
              
            String sql1="select T.tm_id,M.usn,T.pid,P.pname,M.finalmarks from\n"
                    + "project P,team T,marks M\n"
                    + "where P.pid=T.pid and M.pid=P.pid and M.teacher_id='"+idteacher1.getText()+"'";
            DefaultTableModel tb=(DefaultTableModel) viewteam.getModel();
        tb.setRowCount(0);
        try
        {
            String rg[]=new String[5];
         pst5=con.prepareStatement(sql1);
          rs5= pst5.executeQuery();
          
          if(rs5.next())
          {
              
              do
              {
                rg[0]=rs5.getString(1);
                rg[1]=rs5.getString(2);
                rg[2]=rs5.getString(3);
                rg[3]=rs5.getString(4);
                rg[4]=rs5.getString(5);
                
                tb.addRow(rg);
                
              }while(rs5.next());
          }
              
    }                                        
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
              
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrong Teacher Id","Denied",JOptionPane.ERROR_MESSAGE);
          }
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    }//GEN-LAST:event_search1ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        if (usn.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter USN","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (marks1.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Marks1","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (marks2.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Marks2","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (marks3.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Marks3","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (p_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Project ID","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (teacher_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Teacher ID","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (username2.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Username","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (pass.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter Password","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        con=connect.ConnectDB();
        CallableStatement cs;
        String sql= "select * from userdetails where user_name= '" + username2.getText() + "' and password ='" + pass.getText() + "'";
       try {
       pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
          if (rs.next()){
              String sql11="select usn from student where usn='"+usn.getText()+"'";
              pst1=con.prepareStatement(sql11);
              rs1=pst1.executeQuery();
              if(rs1.next())
              {
                  String sql111="select T.pid from team T,student S where S.tm_id=T.tm_id and T.pid='"+p_id.getText()+"' and S.usn='"+usn.getText()+"'";
              pst3=con.prepareStatement(sql111);
              rs3=pst3.executeQuery();
              boolean record=rs3.next();
              if(record)
              {
                  String sql1111="select T.teacher_id from team T,student S where T.tm_id=S.tm_id and T.teacher_id='"+teacher_id.getText()+"' and S.usn='"+usn.getText()+"'";
              pst4=con.prepareStatement(sql1111);
              rs4=pst4.executeQuery();
              boolean recordnew=rs4.next();
              if(recordnew)
              {
             String selectquery="insert into marks(marks1,marks2,marks3,pid,teacher_id,usn) values(?,?,?,?,?,?)";
             pst1=con.prepareStatement(selectquery);
             pst1.setString(1,marks1.getText());
             pst1.setString(2,marks2.getText());
             pst1.setString(3,marks3.getText());
            // pst1.setString(4,"");
             pst1.setString(4,p_id.getText());
             pst1.setString(5,teacher_id.getText());
             pst1.setString(6,usn.getText());
             pst1.execute();
             cs=con.prepareCall("{ call fmarks}");
             cs.executeUpdate();
             JOptionPane.showMessageDialog(null, "Marks Updated");
              }
              else
              {
                JOptionPane.showMessageDialog(null, "Invalid Teacher id!","Access denied",JOptionPane.ERROR_MESSAGE);  
              }
              }
              else
              {
                JOptionPane.showMessageDialog(null, "Invalid Project id!","Access denied",JOptionPane.ERROR_MESSAGE);  
              }
              }
              else
              {
                JOptionPane.showMessageDialog(null, "Invalid USN!","Access denied",JOptionPane.ERROR_MESSAGE);  
              }
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!","Access denied",JOptionPane.ERROR_MESSAGE);
          }
      }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }
    }//GEN-LAST:event_submit2ActionPerformed

    private void usnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_fn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALL_PROJ;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel TID;
    private javax.swing.JLabel TID1;
    private javax.swing.JPanel assigned_projs;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background5;
    private javax.swing.JMenu date;
    private javax.swing.JMenuBar date_time;
    private javax.swing.JTextField idteacher;
    private javax.swing.JTextField idteacher1;
    private javax.swing.JPanel insert_fn;
    private javax.swing.JButton logout;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JTextField marks1;
    private javax.swing.JTextField marks2;
    private javax.swing.JTextField marks3;
    private javax.swing.JButton marks_in;
    private javax.swing.JPanel multiple_fn;
    private javax.swing.JPanel options;
    private javax.swing.JTextField p_id;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel pid;
    private javax.swing.JButton proj_all;
    private javax.swing.JButton proj_wth_marks;
    private javax.swing.JLabel projid;
    private javax.swing.JScrollPane projtable;
    private javax.swing.JButton reset2;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton submit2;
    private javax.swing.JLabel teach_id;
    private javax.swing.JTextField teacher_id;
    private javax.swing.JScrollPane teamtable;
    private javax.swing.JMenu time;
    private javax.swing.JLabel user2;
    private javax.swing.JTextField username2;
    private javax.swing.JTextField usn;
    private javax.swing.JLabel usn1;
    private javax.swing.JTable viewproj;
    private javax.swing.JTable viewteam;
    // End of variables declaration//GEN-END:variables
}
